sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jbcomte/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbcomte/doccker-react npm run test
